<center><img src="redpopcorn.jpg"></center>

**Netflix**! What started in 1997 as a DVD rental service has since exploded into one of the largest entertainment and media companies.

Given the large number of movies and series available on the platform, it is a perfect opportunity to flex your exploratory data analysis skills and dive into the entertainment industry.

You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade!

You have been supplied with the dataset `netflix_data.csv`, along with the following table detailing the column names and descriptions. Feel free to experiment further after submitting!

## The data
### **netflix_data.csv**
| Column | Description |
|--------|-------------|
| `show_id` | The ID of the show |
| `type` | Type of show |
| `title` | Title of the show |
| `director` | Director of the show |
| `cast` | Cast of the show |
| `country` | Country of origin |
| `date_added` | Date added to Netflix |
| `release_year` | Year of Netflix release |
| `duration` | Duration of the show in minutes |
| `description` | Description of the show |
| `genre` | Show genre |

In [98]:
# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

In [99]:
# Start coding here! Use as many cells as you like
netflix_df.head(10)

  show_id  ...             genre
0      s2  ...            Dramas
1      s3  ...     Horror Movies
2      s4  ...            Action
3      s5  ...            Dramas
4      s6  ...  International TV
5      s7  ...     Horror Movies
6      s8  ...            Dramas
7      s9  ...     Horror Movies
8     s10  ...     Horror Movies
9     s11  ...            Dramas

[10 rows x 11 columns]

In [100]:
netflix_df.shape

(4812, 11)

In [101]:
netflix_df.describe()

       release_year     duration
count   4812.000000  4812.000000
mean    2012.711554    99.566708
std        9.517978    30.889305
min     1942.000000     1.000000
25%     2011.000000    88.000000
50%     2016.000000    99.000000
75%     2018.000000   116.000000
max     2021.000000   253.000000

In [102]:
netflix_df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
duration        0
description     0
genre           0
dtype: int64

In [103]:
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   object
 1   type          4812 non-null   object
 2   title         4812 non-null   object
 3   director      4812 non-null   object
 4   cast          4812 non-null   object
 5   country       4812 non-null   object
 6   date_added    4812 non-null   object
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   object
 10  genre         4812 non-null   object
dtypes: int64(2), object(9)
memory usage: 413.7+ KB

In [104]:
netflix_df.duration.describe()

count    4812.000000
mean       99.566708
std        30.889305
min         1.000000
25%        88.000000
50%        99.000000
75%       116.000000
max       253.000000
Name: duration, dtype: float64

In [105]:
durationtry1 = netflix_df.duration.mode()[0]
durationtry1

93

In [106]:
duration_df = netflix_df[['type', 'release_year', 'duration', 'genre']]
duration_df.head()

      type  release_year  duration             genre
0    Movie          2016        93            Dramas
1    Movie          2011        78     Horror Movies
2    Movie          2009        80            Action
3    Movie          2008       123            Dramas
4  TV Show          2016         1  International TV

In [107]:
duration_df.shape

(4812, 4)

In [108]:
# duration_df = duration_df[(duration_df['release_year'] >= 1990) & (duration_df['release_year'] < 2000)]
duration_df = duration_df[duration_df['release_year'].isin(range(1990, 2000))]
duration_df.head()

      type  release_year  duration     genre
6    Movie          1997       119    Dramas
118  Movie          1993       101    Dramas
145  Movie          1998        82  Comedies
167  Movie          1996       108  Comedies
194  Movie          1993       154    Dramas

In [109]:
duration_df.shape

(184, 4)

In [110]:
duration_df = duration_df[duration_df['type'].isin(['Movie']) & duration_df['genre'].isin(['Action'])]
duration_df.shape

(48, 4)

In [111]:
duration = duration_df.duration.mode()[0]
duration

108

In [112]:
short_movie_count = duration_df[duration_df['duration'].isin(range(0, 90))].shape[0]
short_movie_count

7